name: BedWars
version: '${project.version}'
main: com.monitoria.bedwars.BedWars
api-version: '1.20'
author: Bruno D'Luka
commands:
  iniciar_bedwars:
    description: Your description
    usage: /iniciar_bedwars